language: python
dist: xenial
sudo: false
python:
  - "3.6"
install:
  - pip install .
  - pip install python-coveralls
  - pip install pytest-cov
  - pip install nbval
script:
  - pytest tests --cov=wingstructure
  - pytest --nbval-lax examples/
after_success:
  - coveralls
